project:
  type: website

website:
  title: "Mark Spillman"
  site-url: https://mspillman.github.io
  google-analytics: G-EVMREB130B
  navbar:
    right:
      - text: Home
        file: index.qmd
      - about.qmd
      - publications.qmd
      - icon: github
        href: https://github.com/mspillman
      - icon: twitter
        href: https://twitter.com/mspillman
format:
  html:
    theme: cosmo
    css: styles.css



